### ISSUE TITLE
Why is minSdkVersion set to 17?

### ISSUE THREAD

**Issue by gdingenen** [tommus/youtube-android-player-api#1]
The minSdkVersion is set to 17. I can't find any documentation about this on the Youtube Player API  Documentation.

What is the reason for using minSdkVersion 17?

**Comment by tommus** [comment]
There is an information at the [setup page](https://developers.google.com/youtube/android/player/setup) (IntelliJ part, point 4g) which states that it is necessary to select Android 4.2 platform SDK as the project SDK. I've set the minSdkVersion to 17 to avoid compatibility issues.
